server:
  port: 0
spring:
  application:
    name: shopping-store
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_home?currentSchema=shopping_store
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    ru.yandex.practicum: DEBUG
