spring:
  application:
    name: analyzer
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5432/smart_home
    username: analyzer
    password: analyzer
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

grpc:
  client:
    hub-router:
      address: 'static://localhost:59091'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  level:
    ru.yandex.practicum: DEBUG
